In [ ]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Zainier Manombaga"
STUDENT_ID = 3683

In [2]:
# CODE SNIPPET #1
np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)
mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "Std Dev:", std_val)

Zainier Manombaga's Array: [ 62  23  25  13  33  65  18 109  10 114]
Mean: 47.2 Std Dev: 36.747244794678146


In [3]:
# CODE SNIPPET #2
np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)
row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

Zainier Manombaga's Matrix:
 [[23 25 29 13]
 [49 21 39 33]
 [11  1 18 52]]
Row sums: [ 90 142  82]
Column sums: [83 47 86 98]


In [4]:
# CODE SNIPPET #3
np.random.seed(STUDENT_ID)
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)
slice_mid = arr3d[:,1,:]
print("Slice[:,1,:]:\n", slice_mid)

Zainier Manombaga's 3D Array:
 [[[ 6  8 12]
  [12  0  4]
  [ 6  0 10]]

 [[ 0  1  4]
  [ 3  1 12]
  [12  9  9]]

 [[ 1  0  0]
  [ 8  0  6]
  [ 9  8  8]]]
Slice[:,1,:]:
 [[12  0  4]
 [ 3  1 12]
 [ 8  0  6]]


In [5]:
# CODE SNIPPET #4
np.random.seed(STUDENT_ID)
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
filtered = x[(x > STUDENT_ID % 50) & (x < STUDENT_ID % 100)]
print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Zainier Manombaga's Original: [ 62  23  25  13  33  65  18 109  10 114]
Filtered subset: [62 65]


In [6]:
# CODE SNIPPET #5
np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
print("Matrix A:\n", A)
print("Matrix B:\n", B)
product = A @ B
det_A = np.linalg.det(A)
print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[23 25]
 [29 13]]
Matrix B:
 [[49 21]
 [39 33]]
A @ B:
 [[2102 1308]
 [1928 1038]]
Determinant of A: -426.00000000000017


In [7]:
# CODE SNIPPET #6
angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)
print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

Zainier Manombaga's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [8]:
# CODE SNIPPET #7
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Zainier Manombaga's Modified 4x4 Array:
 [[ 0 25  0 13]
 [49 21 39 33]
 [ 0  1  0 52]
 [18 45 45 10]]


In [9]:
# CODE SNIPPET #8
np.random.seed(STUDENT_ID)
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores >= STUDENT_ID % 70, 'Pass', 'Fail')
print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

Zainier Manombaga's Scores: [ 61  22  24  12  32  64  17 108   9 113]
Grades: ['Pass' 'Fail' 'Fail' 'Fail' 'Fail' 'Pass' 'Fail' 'Pass' 'Fail' 'Pass']


In [10]:
# CODE SNIPPET #9
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
flat_arr = arr.flatten()
transposed_arr = arr.T
print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original array:
 [[23 25 29 13]
 [49 21 39 33]
 [11  1 18 52]]
Flattened: [23 25 29 13 49 21 39 33 11  1 18 52]
Transposed:
 [[23 49 11]
 [25 21  1]
 [29 39 18]
 [13 33 52]]


In [11]:
# CODE SNIPPET #10
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = arr % 2 == 0
arr[mask] = -1
print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[23 25 29]
 [13 49 21]
 [39 33 11]]


In [12]:
# CODE SNIPPET #11
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Name': [STUDENT_NAME]*5,
    'Score': np.random.randint(STUDENT_ID % 50, STUDENT_ID % 100 + 50, 5),
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5)
})
print(df)

                Name  Score  YearsCodePro
0  Zainier Manombaga     94             0
1  Zainier Manombaga     55             4
2  Zainier Manombaga     57             6
3  Zainier Manombaga    125             0
4  Zainier Manombaga     45            10


In [13]:
# CODE SNIPPET #12
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()
print(avg_salary)

EdLevel
Bachelor    100940.5
Master      102481.0
PhD         124760.0
Name: ConvertedComp, dtype: float64


In [14]:
# CODE SNIPPET #13
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(top5)

       Country  ConvertedComp
1          USA         133974
2           UK         124760
3       Canada         109852
0  Philippines          92029
4      Germany          70988


In [15]:
# CODE SNIPPET #14
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Name': [STUDENT_NAME]*5,
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5)
})
high_exp = df[df['YearsCodePro'] > STUDENT_ID % 10]
print(high_exp)

                Name  YearsCodePro
0  Zainier Manombaga             6
1  Zainier Manombaga             8
2  Zainier Manombaga            12
3  Zainier Manombaga            12


In [16]:
# CODE SNIPPET #15
np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})
bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)

   ConvertedComp   Bracket
0          92029   50-100k
1         133974  100-150k
2         124760  100-150k
3         109852  100-150k
4          70988   50-100k


In [17]:
# CODE SNIPPET #16
np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})
df['LogComp'] = np.log(df['ConvertedComp'])
print(df)

   ConvertedComp    LogComp
0          92029  11.429859
1         133974  11.805401
2         124760  11.734147
3         109852  11.606889
4          70988  11.170266


In [18]:
# CODE SNIPPET #17
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5),
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
corr_matrix = df.corr()
print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000      -0.619149
ConvertedComp     -0.619149       1.000000


In [19]:
# CODE SNIPPET #18
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean', 'median', 'std']).reset_index()
print(summary)

    EdLevel      mean    median           std
0  Bachelor  100940.5  100940.5  12602.764161
1    Master  102481.0  102481.0  44537.827720
2       PhD  124760.0  124760.0           NaN


In [20]:
# CODE SNIPPET #19
np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})
threshold = 110000
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')
print(df)


   ConvertedComp HighPay
0          92029      No
1         133974     Yes
2         124760     Yes
3         109852      No
4          70988      No


In [21]:
# CODE SNIPPET #20
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean', 'max'])
print(top_countries)

                 mean     max
Country                      
Canada       109852.0  109852
Germany       70988.0   70988
Philippines   92029.0   92029
UK           124760.0  124760
USA          133974.0  133974
