In [1]:
# PROCEDURE 1: Creating NumPy Arrays
import numpy as np
import pandas as pd

# Original Code
years_exp = np.array([1, 3, 5, 7, 10])
print("Years of Experience:", years_exp)
 
salaries = np.array([[50, 60, 70], [80, 90, 100]])
print("Salary Matrix:\n", salaries)
 
zeros_array = np.zeros((2, 2))
ones_array = np.ones((2, 3))
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

Years of Experience: [ 1  3  5  7 10]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [2]:
# ── Try It ────────────────────────────────────────────────
# Add 2 more data points to years_exp and salaries
years_exp = np.array([1, 3, 5, 7, 10, 12, 15])
print("\n[TRY IT] Updated Years of Experience:", years_exp)
 
salaries = np.array([[50, 60, 70], [80, 90, 100], [110, 120, 130], [140, 150, 160]])
print("[TRY IT] Updated Salary Matrix:\n", salaries)
 
# Create a 3x3 identity matrix
identity_3x3 = np.eye(3)
print("[TRY IT] 3x3 Identity Matrix:\n", identity_3x3)


[TRY IT] Updated Years of Experience: [ 1  3  5  7 10 12 15]
[TRY IT] Updated Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]
 [110 120 130]
 [140 150 160]]
[TRY IT] 3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
# PROCEDURE 2: Array Operations
years_exp = np.array([1, 3, 5, 7, 10])  # reset for clean demo
 
# Original Code
exp_plus_5 = years_exp + 5
print("\nYears + 5:", exp_plus_5)
 
exp_times_2 = years_exp * 2
print("Years * 2:", exp_times_2)
 
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)


Years + 5: [ 6  8 10 12 15]
Years * 2: [ 2  6 10 14 20]
Dot Product: 32


In [4]:
# ── Try It ────────────────────────────────────────────────
# Subtraction and division
exp_minus_1 = years_exp - 1
exp_div_2   = years_exp / 2
print("\n[TRY IT] Years - 1:", exp_minus_1)
print("[TRY IT] Years / 2:", exp_div_2)
 
# np.exp() and np.log()
print("[TRY IT] np.exp(years_exp):", np.exp(years_exp))
print("[TRY IT] np.log(years_exp):", np.log(years_exp))
 


[TRY IT] Years - 1: [0 2 4 6 9]
[TRY IT] Years / 2: [0.5 1.5 2.5 3.5 5. ]
[TRY IT] np.exp(years_exp): [2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
 2.20264658e+04]
[TRY IT] np.log(years_exp): [0.         1.09861229 1.60943791 1.94591015 2.30258509]


In [5]:
# PROCEDURE 3: Indexing and Slicing
years_exp = np.array([1, 3, 5, 7, 10])
salaries  = np.array([[50, 60, 70], [80, 90, 100]])
 
# Original Code
print("\nFirst year of experience:", years_exp[0])
print("First two salaries:", salaries[0, :2])
print("Second column salaries:", salaries[:, 1])
print("Last year of experience:", years_exp[-1])


First year of experience: 1
First two salaries: [50 60]
Second column salaries: [60 90]
Last year of experience: 10


In [6]:
# ── Try It ────────────────────────────────────────────────
# Reverse array using slicing
print("\n[TRY IT] Reversed years_exp:", years_exp[::-1])
 
# Slice 2D array for subgroups
print("[TRY IT] First row, all columns:", salaries[0, :])
print("[TRY IT] All rows, last column:", salaries[:, -1])
print("[TRY IT] Bottom-right 2x2 subgroup:\n", salaries[0:2, 1:3])



[TRY IT] Reversed years_exp: [10  7  5  3  1]
[TRY IT] First row, all columns: [50 60 70]
[TRY IT] All rows, last column: [ 70 100]
[TRY IT] Bottom-right 2x2 subgroup:
 [[ 60  70]
 [ 90 100]]


In [7]:
# PROCEDURE 4: Reshaping and Dimensions

# Original Code
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("\nReshaped Experience Array:\n", reshaped_exp)
 
flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)
 
print("Transposed Array:\n", reshaped_exp.T)


Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [8]:
# ── Try It ────────────────────────────────────────────────
# Reshape into different dimensions
arr_3x2 = np.arange(1, 7).reshape(3, 2)
arr_1x6 = np.arange(1, 7).reshape(1, 6)
arr_6x1 = np.arange(1, 7).reshape(6, 1)
print("\n[TRY IT] Reshaped to 3x2:\n", arr_3x2)
print("[TRY IT] Reshaped to 1x6:", arr_1x6)
print("[TRY IT] Reshaped to 6x1:\n", arr_6x1)


[TRY IT] Reshaped to 3x2:
 [[1 2]
 [3 4]
 [5 6]]
[TRY IT] Reshaped to 1x6: [[1 2 3 4 5 6]]
[TRY IT] Reshaped to 6x1:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [9]:
# PROCEDURE 5: Broadcasting in NumPy
salaries = np.array([[50, 60, 70], [80, 90, 100]])
 
# Original Code
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus
print("\nSalaries after bonus:\n", salaries_with_bonus)


Salaries after bonus:
 [[ 55  70  85]
 [ 85 100 115]]


In [10]:
# ── Try It ────────────────────────────────────────────────
# Multiply by a scaling factor using broadcasting
scaling_factor = np.array([1.1, 1.2, 1.15])
scaled_salaries = salaries * scaling_factor
print("[TRY IT] Salaries after scaling:\n", scaled_salaries)
 
# Broadcast a scalar
salaries_plus_flat_bonus = salaries + 5
print("[TRY IT] All salaries + flat 5k:\n", salaries_plus_flat_bonus)

[TRY IT] Salaries after scaling:
 [[ 55.   72.   80.5]
 [ 88.  108.  115. ]]
[TRY IT] All salaries + flat 5k:
 [[ 55  65  75]
 [ 85  95 105]]


In [11]:
# PROCEDURE 6: Statistical Operations

years_exp = np.array([1, 3, 5, 7, 10])
salaries  = np.array([[50, 60, 70], [80, 90, 100]])
 
# Original Code
print("\nMean experience:", np.mean(years_exp))
print("Std deviation of experience:", np.std(years_exp))
print("Max salary:", np.max(salaries), "| Min salary:", np.min(salaries))
print("Sum of all salaries:", np.sum(salaries))


Mean experience: 5.2
Std deviation of experience: 3.1240998703626617
Max salary: 100 | Min salary: 50
Sum of all salaries: 450


In [12]:
# ── Try It ────────────────────────────────────────────────
print("\n[TRY IT] Median of years_exp:", np.median(years_exp))
print("[TRY IT] 25th percentile:", np.percentile(years_exp, 25))
print("[TRY IT] 75th percentile:", np.percentile(years_exp, 75))
print("[TRY IT] Median of salaries:", np.median(salaries))


[TRY IT] Median of years_exp: 5.0
[TRY IT] 25th percentile: 3.0
[TRY IT] 75th percentile: 7.0
[TRY IT] Median of salaries: 75.0


In [13]:
# PROCEDURE 7: NumPy Functions on Arrays
 
# Original Code
angles = np.array([0, np.pi/4, np.pi/2])
print("\nSine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))
 
salaries = np.array([[50, 60, 70], [80, 90, 100]])
salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)


Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270]


In [14]:
# ── Try It ────────────────────────────────────────────────
sample_arr = np.array([1, 4, 9, 16, 25])
print("\n[TRY IT] np.sqrt():", np.sqrt(sample_arr))
print("[TRY IT] np.log():", np.log(sample_arr))
 
# apply_along_axis with a custom function (column-wise max)
col_max = np.apply_along_axis(np.max, 0, salaries)
print("[TRY IT] Max per column:", col_max)
 
# Custom function: normalize a row (subtract min, divide by range)
def normalize(row):
    return (row - np.min(row)) / (np.max(row) - np.min(row))
 
normalized = np.apply_along_axis(normalize, 1, salaries)
print("[TRY IT] Row-normalized salaries:\n", normalized)


[TRY IT] np.sqrt(): [1. 2. 3. 4. 5.]
[TRY IT] np.log(): [0.         1.38629436 2.19722458 2.77258872 3.21887582]
[TRY IT] Max per column: [ 80  90 100]
[TRY IT] Row-normalized salaries:
 [[0.  0.5 1. ]
 [0.  0.5 1. ]]


In [15]:
# PROCEDURE 8: Integrating NumPy and Pandas
# ============================================================

# Original Code
np.random.seed(42)
data = np.random.randint(1, 50, size=(5, 3))
 
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("\nGenerated Data:\n", df_data)
 
df_data['Log_X']  = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("DataFrame with NumPy Transformations:\n", df_data)
 
print("Correlation Matrix:\n", df_data.corr(numeric_only=True))


Generated Data:
     X   Y   Z
0  39  29  15
1  43   8  21
2  39  19  23
3  11  11  24
4  36  40  24
DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0  39  29  15  3.663562  5.385165
1  43   8  21  3.761200  2.828427
2  39  19  23  3.663562  4.358899
3  11  11  24  2.397895  3.316625
4  36  40  24  3.583519  6.324555
Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000  0.267358 -0.422038  0.996465  0.261697
Y       0.267358  1.000000 -0.129194  0.343478  0.994609
Z      -0.422038 -0.129194  1.000000 -0.409283 -0.163058
Log_X   0.996465  0.343478 -0.409283  1.000000  0.339021
Sqrt_Y  0.261697  0.994609 -0.163058  0.339021  1.000000


In [16]:
# ── Try It ────────────────────────────────────────────────
print("\n[TRY IT] Column Means via np.mean():")
print(np.mean(df_data[['X', 'Y', 'Z']].values, axis=0))
 
print("\n[TRY IT] Column Medians via np.median():")
print(np.median(df_data[['X', 'Y', 'Z']].values, axis=0))
 
df_data['Squared_Z'] = np.square(df_data['Z'])
df_data['Exp_X']     = np.exp(df_data['X'])
print("[TRY IT] DataFrame with np.square() and np.exp():\n",
      df_data[['X', 'Z', 'Squared_Z', 'Exp_X']])
 


[TRY IT] Column Means via np.mean():
[33.6 21.4 21.4]

[TRY IT] Column Medians via np.median():
[39. 19. 23.]
[TRY IT] DataFrame with np.square() and np.exp():
     X   Z  Squared_Z         Exp_X
0  39  15        225  8.659340e+16
1  43  21        441  4.727839e+18
2  39  23        529  8.659340e+16
3  11  24        576  5.987414e+04
4  36  24        576  4.311232e+15


In [17]:
# PROCEDURE 9: Importing and Summarizing Data Using Pandas
 
# Original Code
df_data[['X', 'Y', 'Z']].to_csv('sample_data.csv', index=False)
print("\nData saved to 'sample_data.csv'.")
 
df_imported = pd.read_csv('sample_data.csv')
print("Imported DataFrame:\n", df_imported)
 
summary_stats = df_imported.describe()
print("Summary Statistics:\n", summary_stats)
 
print("Column Means:\n", df_imported.mean(numeric_only=True))
print("Column Standard Deviations:\n", df_imported.std(numeric_only=True))
 


Data saved to 'sample_data.csv'.
Imported DataFrame:
     X   Y   Z
0  39  29  15
1  43   8  21
2  39  19  23
3  11  11  24
4  36  40  24
Summary Statistics:
                X          Y          Z
count   5.000000   5.000000   5.000000
mean   33.600000  21.400000  21.400000
std    12.876335  13.202273   3.781534
min    11.000000   8.000000  15.000000
25%    36.000000  11.000000  21.000000
50%    39.000000  19.000000  23.000000
75%    39.000000  29.000000  24.000000
max    43.000000  40.000000  24.000000
Column Means:
 X    33.6
Y    21.4
Z    21.4
dtype: float64
Column Standard Deviations:
 X    12.876335
Y    13.202273
Z     3.781534
dtype: float64


In [18]:
# ── Try It ────────────────────────────────────────────────
df_imported['Sum_XY'] = df_imported['X'] + df_imported['Y']
df_imported['Diff_ZX'] = df_imported['Z'] - df_imported['X']
print("\n[TRY IT] DataFrame with new calculated columns:\n", df_imported)
 
df_imported.to_csv('sample_data_modified.csv', index=False)
print("[TRY IT] Modified DataFrame saved to 'sample_data_modified.csv'.")


[TRY IT] DataFrame with new calculated columns:
     X   Y   Z  Sum_XY  Diff_ZX
0  39  29  15      68      -24
1  43   8  21      51      -22
2  39  19  23      58      -16
3  11  11  24      22       13
4  36  40  24      76      -12
[TRY IT] Modified DataFrame saved to 'sample_data_modified.csv'.


In [24]:
# Step 1: Load the Stack Overflow 2023 Developer Survey dataset
df_kaggle = pd.read_csv('survey_results_public.csv')
print("Loaded Dataset:\n", df_kaggle.head())

# Step 2: Select relevant columns

df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']]
print("Subset of Data:\n", df_subset.head())

# Step 3: Clean the data by dropping rows with missing values
df_clean = df_subset.dropna()
print("Cleaned Data:\n", df_clean.head())

# Step 4: Convert YearsCodePro to numbers first
df_clean['YearsCodePro'] = pd.to_numeric(df_clean['YearsCodePro'], errors='coerce')

# Now you can categorize experience without the TypeError
df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 'Junior')

# Step 5: Group by Country and ExperienceLevel
# (Note: Using 'ConvertedCompYearly' as we found earlier)
grouped_data = df_clean.groupby(['Country', 'ExperienceLevel'])['ConvertedCompYearly'].mean()
print("Grouped Average Salary:\n", grouped_data.head())

# Step 6: Reset index for readability
grouped_data = grouped_data.reset_index()
print("Formatted Grouped Data:\n", grouped_data.head())

Loaded Dataset:
    ResponseId     Q120                      MainBranch              Age  \
0           1  I agree                   None of these  18-24 years old   
1           2  I agree  I am a developer by profession  25-34 years old   
2           3  I agree  I am a developer by profession  45-54 years old   
3           4  I agree  I am a developer by profession  25-34 years old   
4           5  I agree  I am a developer by profession  25-34 years old   

                                          Employment  \
0                                                NaN   
1                                Employed, full-time   
2                                Employed, full-time   
3                                Employed, full-time   
4  Employed, full-time;Independent contractor, fr...   

                             RemoteWork  \
0                                   NaN   
1                                Remote   
2  Hybrid (some remote, some in-person)   
3  Hybrid (some remote,